spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
msg:
  sys_props_switch: 3
messagesource:
  basename: i18n/messages
  cache-seconds: 3600
  encoding: UTF-8    
