spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
  rabbitmq:
    host: 10.16.117.191
    port: 31129
msg:
  sys_props_switch: 3
messagesource:
  basename: i18n/messages
  cache-seconds: 3600
  encoding: UTF-8    
profiles: user
